
name: CD - DockerHub

on:
  push:
    branches: [ "main"]

jobs:
  Docker: 
    name: cd-docker hub
    runs-on: ubuntu-latest
    steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKEHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: vitorlassen/itaguacu-front